### ISSUE TITLE
Sed on a mac is different than sed on linux

### ISSUE THREAD

**Issue by noahwsmith** [Islandora-Devops/isle-dc#115]
https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux

This means that our Makefile needs those extra ` ''` right after the `-i`.

PR coming right up...

**Comment by rosiel** [comment]
Thanks for the PR - it indeed works on Mac!

Discussion on the Oct 7 Tech call: Gee, we should probably test on Windows too.

@emudojo @birkland ? 

Many thanks! 
(editing to also tag @marksandford  - hi! I hear you're a windows user too?)
