### ISSUE TITLE
Explain why it's islandora-isle-dc.traefik.me

### ISSUE THREAD

**Issue by rosiel** [Islandora-Devops/isle-dc#120]
So, I realize that there are reasons for using traefik.me that have to do with "treating the URLs as though they were fully qualified domain names" which probably helps the isle containers talk to each other. But for users who are new to sandboxes, https://islandora-isle-dc.traefik.me/ is long and unwieldy and opaque and unfriendly. 

I think that it's FAR better to have a confusing and long URL rather than a flaky URL or something that requires the user to go into their hosts file or do extra configurations, so can we discuss the reasons it is the way it is, and whether there is a "right way" to change it to be more new-user friendly.

e.g. 
- I notice that the string 'traefik.me' is not islandora-y at all, is there a simple/easy/built-for-purpose way to provide a different fake domain like maybe isle.dev, or islandora.dev?
- I notice that it's three parts (blah.traefik.me) and not two - is there a simple/easy/built-for-purpose way for traefik.me to a default? 
- I notice that the first url segment islandora-isle-dc is long and I'm not sure why all the parts are needed. It seems that we are setting up "our stuff" at FOO-isle-dc.traefik.me. Is this just for "namespacing" these as part of isle-dc, because you might have other isle stuff (that's not isle-dc) running on the same traefik.me? Would there be a disadvantage to changing the drupal's url to just 'islandora.traefik.me' or 'drupal.traefik.me'?

Also, what's the big picture? What are all the *.traefik.me's that may be affected by this?

**Comment by ian-j-stewart** [comment]
I believe an alias (i.e. domain name or whatever) can be created for this site simply by adding it to two places in the docker-compose.yml file. (n.b. should probably be edited in the docker-compose.drupal.yml file before the make command is run so that the change is persistent. 

Be careful when editing this file as the quote character is ` rather than the usual '. 

So for example, in my test site I where I have a domainname, DOMAIN.COM

  drupal:
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME-isle-dc}-drupal.loadbalancer.server.port=80
      - traefik.http.middlewares.drupal-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.drupal-redirectscheme.redirectscheme.permanent=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME-isle-dc}-drupal_http.service=${COMPOSE_PROJECT_NAME-isle-dc}-drupal
      - traefik.http.routers.${COMPOSE_PROJECT_NAME-isle-dc}-drupal_http.entrypoints=http
      - traefik.http.routers.${COMPOSE_PROJECT_NAME-isle-dc}-drupal_http.rule=Host(**`DOMAIN.COM`**,`islandora-${COMPOSE_PROJECT_NAME-isle-dc}.${DRUPAL_SITE_HOST-traefik.me}`,`islandora-${COMPOSE_PROJECT_NAME-isle-dc}-${DRUPAL_SITE_HOST-traefik.me}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME-isle-dc}-drupal_http.middlewares=drupal-redirectscheme
      - traefik.http.routers.${COMPOSE_PROJECT_NAME-isle-dc}-drupal_https.entrypoints=https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME-isle-dc}-drupal_https.rule=Host(**`DOMAIN.COM`**, `islandora-${COMPOSE_PROJECT_NAME-isle-dc}.${DRUPAL_SITE_HOST-traefik.me}`,`islandora-${COMPOSE_PROJECT_NAME-isle-dc}-${DRUPAL_SITE_HOST-traefik.me}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME-isle-dc}-drupal_https.tls=true
    networks:
      default:
        # Allow services (like Matomo) to use the edge name to reference this service in addition to `drupal`.
        aliases:
            - islandora-${COMPOSE_PROJECT_NAME-isle-dc}.${DRUPAL_SITE_HOST-traefik.me}
            - islandora-${COMPOSE_PROJECT_NAME-isle-dc}-${DRUPAL_SITE_HOST-traefik.me}
      gateway:

**Comment by rosiel** [comment]
Super good to know! That's a real domain, though!

My context was: I was writing the documentation on "how to spin up Docker as a development environment" and for folks who are used to dev VMs, domains like 'localhost' or 'localhost:8080' or 'drupal.dev' are more common and understandable. What's with the super long https://islandora-isle-dc.traefik.me/ ? Is there a reasonable thing that it could be instead that's not so long? 

I assume that the situation you described is more of a "production" deployment (or a shared development or staging environment). I am making some assumptions here:
- that method you describe only works if you have a static ip address (i.e. a server, a cloud server, a computer on a commercial internet connection with a fixed IP) and a spare domain to use
- most development these days is done on local computers and not on external servers
- most developers don't have fixed IPs on their local computers
- most devs don't have a own spare domain

**Comment by ian-j-stewart** [comment]
Yes, fair. I have been working through how one could deploy in production for a personal project I am interested in pursuing. Maybe I can add a comment here, however, as I didn't at first take this page as being about deploying for development purposes only. 

https://islandora.github.io/documentation/installation/docker-compose/

I wonder if / when documentation for deploying to production will be written? As a starting point, I think such documentation would have to address the domain name issue, the SSL issue, highlight when and where to change the default passwords (n.b. probably before running the first make command).

**Comment by rosiel** [comment]
Yes - i understand that there's a `make prod` command but that it's not fully functional yet. 

When that's ready, I think it would make sense to split out the 'how to launch a simple dev ISLE' from 'ISLE Reference Guide' and 'What you have to do to use ISLE in production' . (neither of which exist yet).

I was recently reminded of Conway's Law: "Your software's structure will reflect your organizational structure". 

Does there need to be a separate section for "ISLE" or is it just "installing Islandora"?

**Comment by ian-j-stewart** [comment]
The idea of a make prod command is interesting. Would it be worth creating an issue specific to the fleshing out of that?

**Comment by rosiel** [comment]
@dannylamb

**Comment by noahwsmith** [comment]
I believe this is one of the objectives for the upcoming ISLE sprint https://islandora.ca/content/isle-sprint-november-2nd-13th

**Comment by rosiel** [comment]
This seems to have been addressed in the code, but now the tutorial and readme are incorrect.

Tutorial PR: https://github.com/Islandora/documentation/pull/1720
README ticket: https://github.com/Islandora/documentation/issues/1712
