### ISSUE TITLE
PHP Fatal error:  Interface 'Psr\EventDispatcher\EventDispatcherInterface' not found in /var/www/drupal/web/modules/copy/contrib/search_api_solr/src/Solarium/EventDispatcher/Psr14Bridge.php on line 12

### ISSUE THREAD

**Issue by ian-j-stewart** [Islandora-Devops/isle-dc#124]
I get the following error when running make hydrate as the last step of the following install process. 

Installation process: make codebase from demo, docker-compose up, make hydrate. 

PHP Fatal error:  Interface 'Psr\EventDispatcher\EventDispatcherInterface' not found in /var/www/drupal/web/modules/copy/contrib/search_api_solr/src/Solarium/EventDispatcher/Psr14Bridge.php on line 12

I believe this might be a PhP version issue, with PHP 7.3 running in the drupal container. 

The following issue / patch didn't resolve this for me:  https://www.drupal.org/project/search_api_solr/issues/3150214

**Comment by joecorall** [comment]
The `make demo` command has been replaced by documentation.

```
$ make demo
make demo has been removed. To create a demo site, please follow the instructions at https://islandora.github.io/documentation/installation/docker-local/
```
