### ISSUE TITLE
BusyBox patch needs to be replaced by GNU patch on the drupal image

### ISSUE THREAD

**Issue by emudojo** [Islandora-Devops/isle-dc#128]
when attempting to apply a patch using composer we get errors, until we manually do apk add patch to replace the one that comes bundled with GNU's one

![image](https://user-images.githubusercontent.com/445995/98997860-d6da8080-24fa-11eb-9237-208fbb52bb8d.png)

**Comment by emetsger** [comment]
@emudojo Just saw this, if you look at https://github.com/Islandora-Devops/isle-buildkit/pull/79, GNU patch has been added to the `drupal` container.  You may need to insure you're using a recent buildkit image.

**Comment by emudojo** [comment]
Closing thanks.
