### ISSUE TITLE
Does not work for " https://islandora.traefik.me/"

### ISSUE THREAD

**Issue by saga0914** [Islandora-Devops/isle-dc#139]
First, I follow this document (https://github.com/Islandora-Devops/isle-dc)

Problem: 
When I put URL: "http://islandora-isle-dc.traefik.me/"
![1](https://user-images.githubusercontent.com/7763459/108073227-c70c9400-7035-11eb-98bf-b3b5fe46e4ef.PNG)

In steps from the documents
![image](https://user-images.githubusercontent.com/7763459/108073393-fa4f2300-7035-11eb-82c6-f7f9e73acf1f.png)

When I wrote "make" , it does not create docker.compose.env.yml 
this is all I got
![image](https://user-images.githubusercontent.com/7763459/108073611-3d10fb00-7036-11eb-8f98-40f87df81e65.png)

When I write " docker-compose up", I got this error.
![1](https://user-images.githubusercontent.com/7763459/108073990-aee94480-7036-11eb-9c21-282f1dcdcdc2.PNG)

However, when I typed "docker-compose ps", everything is up
![image](https://user-images.githubusercontent.com/7763459/108073927-9bd67480-7036-11eb-932a-02c2c831d586.png)

Could you guide me to fix it, please?

**Comment by noahwsmith** [comment]
Quick thing- try https://islandora.traefik.me - maybe the docs are out of date.

**Comment by saga0914** [comment]
> Quick thing- try https://islandora.traefik.me - maybe the docs are out of date.

I tried the URL,but it has same error.
![image](https://user-images.githubusercontent.com/7763459/108075211-194eb480-7038-11eb-84df-9b9dfa148089.png)

**Comment by mjordan** [comment]
`docker-compose up -d` runs clean, no errors as above, and I am getting a 404, not an ERR_CONNECTION_REFUSED.

But like above, `make` doesn't create a  `docker-compose.env.yml`.

**Comment by noahwsmith** [comment]
@dannylamb just released a bunch of code - I don't have time to verify or fix right now, but maybe he could?

**Comment by saga0914** [comment]
> `docker-compose up -d` runs clean, no errors as above, and I am getting a 404, not an ERR_CONNECTION_REFUSED.
> 
> But like above, `make` doesn't create a `docker-compose.env.yml`.

For my understanding, "docker-compose up -d" means hiding the running process so it does not mean working well (I think)
