### ISSUE TITLE
Timed out waiting for database connection

### ISSUE THREAD

**Issue by saga0914** [Islandora-Devops/isle-dc#149]
![image](https://user-images.githubusercontent.com/7763459/112887274-f71d6d00-90a0-11eb-94b3-31c6558fecd9.png)

I was in the step : make demo

Could you guide me to fix that, please?

**Comment by dannylamb** [comment]
Hi @saga0914, is this from the `development` branch? Also, can you confirm the mariadb container is running with `docker ps -a`?

**Comment by saga0914** [comment]
I think I download the project from https://github.com/Islandora-Devops/isle-dc . I guess it is 1.0.0 Alpha 1 ?
When I typed the command, mariadb_1 is up but drupal_1 and crayfits_1 are Exited.

**Comment by dannylamb** [comment]
There were some issues with that build. We've addressed a lot of it recently on the `development` branch.  Would you mind trying that out and letting me know?

If it's still problematic after that, we'll have to get into how you're running it, `make demo` vs `make local` and try to further diagnose.

**Comment by saga0914** [comment]
I tried on the development branch and it is same error "Waiting for 3306 on mariadb to open"
Also, I tried "make local" in development branch and this is issue:
![image](https://user-images.githubusercontent.com/7763459/113002064-6fd30680-913f-11eb-9926-322a2689e64c.png)

**Comment by dannylamb** [comment]
@saga0914 Could you pop into one of the other containers that manage to stay up and see if you can log into mysql?

Supposing the fcrepo container is up, try

```
$ docker-compose exec -it fcrepo with-contenv bash
```

to log into a shell, and then

```
$ mysql -u root -ppassword -h mariadb
```

to open the client.  Depending on how that goes, we can try some other things to figure out what's going on.

**Comment by saga0914** [comment]
Sorry for late response. Now, When I tried to "make demo" in development branch, it says:
![image](https://user-images.githubusercontent.com/7763459/114399298-c5130d00-9b6e-11eb-9128-5b2331b1c8d6.png)

**Comment by joecorall** [comment]
The `make demo` command has been replaced by documentation.

```
$ make demo
make demo has been removed. To create a demo site, please follow the instructions at https://islandora.github.io/documentation/installation/docker-local/
```
