### ISSUE TITLE
Use live and template secrets so git won't complain

### ISSUE THREAD

**Issue by Tristaan** [Islandora-Devops/isle-dc#165]
As I have seen this in other projects I recommend this be done here as well.

So what I recommend is that the secrets folder has two subfolders called `live/` and `template/`. The template folder should have all the secrets in it that are required by docker-compose and should be left untouched. Then there should be a make command used to generate secrets inside the live folder (with or without password and certificate generation). The live folder should be excluded with .gitignore. This is quite practical for not commiting local changes to the secrets and no complains from git when pulling new changes when deploying.

I need some feedback if this feature is practical so I can then make it.

**Comment by noahwsmith** [comment]
I like this approach. The only flaw I see is that for some secrets you may want to set a value and have it stick, e.g. https://github.com/Islandora-Devops/isle-dc/blob/development/secrets/DRUPAL_DEFAULT_CONFIGDIR . How would that be accomplished in this structure?

CC @g7morris who I know is also interested in this topic.

**Comment by Tristaan** [comment]
The generator would generate from existing template files and would just
treat some files as exceptions and act accordingly. Nice that you pointed
that out.
So, a Makefile command that generates secrets, this command will have three important variables, one for all the secrets that should be built with a a password generator, one for all the secrets that are certificates (here are a couple of exceptions, note handle). Then the third var will be for secrets which don't require editing and should just be copied in place.

I plan to create this with two for loops and a simple copy command. one for loop for passwords and the other for certificates, which will contain some ifs for the exceptions.
This way must be maintained, because secrets can change. The second way (which requires no maintenance) is to just copy the secrets inplace and leave the editing to the user.

**Comment by noahwsmith** [comment]
Ok- sounds like an excellent approach. I'd say go for it!

Other interested parties may be @dannylamb and @nigelgbanks

**Comment by dannylamb** [comment]
I have no issues with that approach @Tristaan . Sounds better than live editing secrets.
