### ISSUE TITLE
Wrap boolean values in quotes to support docker-compose v2

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-dc#166]
Errors like the following arise if using docker-compose V2.

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/487373/124947474-c33ed580-e007-11eb-9389-4bda9a0a74d9.png">

```bash
services.fcrepo.environment.FCREPO_DISABLE_SYN must be a string, number or null
```

They can be resolved by putting those variables in double quotes. See:

https://github.com/docker/compose/issues/8097

**Comment by dannylamb** [comment]
@dwilcox ran into this, too.  It's a thing.  We should probably jump on this one soon.

**Comment by DonRichards** [comment]
This ticket appears not to be relevant anymore. I'm closing it but feel free to reopen it if you disagree.

**Comment by DonRichards** [comment]
I personally use Docker Compose version v2.10.2 to run ISLE
