### ISSUE TITLE
make local: error while doing make install

### ISSUE THREAD

**Issue by Tristaan** [Islandora-Devops/isle-dc#182]
Hello,
there is an error happening while running make local, the error happens while calling `install-drupal-site.sh`, I don't know the exact parameters passed, but there must be something wrong with them.
So running make install triggers the following error:
```
Installing site.
 [notice] Starting Drupal installation. This takes a while.

In install.core.inc line 2300:

  Database settings:

  Array
```
To circumvent this issue I did a manual site install using drush inside the container with `drush site:install --use-existing-config minimal`.
I think the database parameter is passed wrong. Here I want to point out that why is it even necessary to pass these parameters, why not just use settings.php?

**Comment by Tristaan** [comment]
Found the culprit, the settings.php file does not get regenerated, it stays the same on every rebuild. so removing settings.php is necessary before running make local, this is because of different secrets on every recreation. so what should be done is a removal of settings.php if an existing codebase is used. I have a snippet ready:
```Makefile
local:
...
	if [ -z "$$(ls -A $(CURDIR)/codebase)" ]; then \
		docker container run --rm -v $(CURDIR)/codebase:/home/root $(REPOSITORY)/nginx:$(TAG) with-contenv bash -lc 'composer create-project drupal/recommended-project:^9.1 /tmp/codebase; mv /tmp/codebase/* /home/root; cd /home/root; composer config minimum-stability dev; composer require islandora/islandora:dev-8.x-1.x; composer require drush/drush:^10.3'; \
	elif [ -z "$$(ls -A $(SRC)/web/sites/default/settings.php)" ]; then \
		sudo rm $(SRC)/web/sites/default/settings.php; \
	fi
...
```

Need some confirmation that it's a good idea.

**Comment by joecorall** [comment]
The `make local` command has been replaced by documentation.

```
$ make local
make local has been removed. To create a demo site, please follow the instructions at https://islandora.github.io/documentation/installation/docker-local/
```
