### ISSUE TITLE
Make local and make demo need to be updated to use Islandora 2.x

### ISSUE THREAD

**Issue by noahwsmith** [Islandora-Devops/isle-dc#192]
From @rosiel 
> there seems to be no way to use isle to get the latest islandora code, since we’re on 2.x now. Can someone help me to update the composer files where they need to be adjusted? Thanks!

**Comment by kayakr** [comment]
The current demo (isle-dc release `islandora/drupal:1.0.0-alpha-11`) installs Drupal 8.9, that is [EOL from 2 November 2021](https://www.drupal.org/psa-2021-06-29).
Per @rosiel's question it's not clear how to update the demo codebase.

`docker-compose exec -T drupal with-contenv bash -lc 'cat composer.json'` shows the requested drupal core, e.g.  `"drupal/core": "^8.9"`

This should be updated to `drupal/core-recommended:^9.3` or similar.

I'm only guessing here, but does the isle-buildkit demo Dockerfile need to be updated to a new COMMIT hash? 
https://github.com/Islandora-Devops/isle-buildkit/blob/main/demo/Dockerfile

Should isle-dc demo continue to rely on https://github.com/dannylamb/islandora-sandbox or switch to https://github.com/Islandora-Devops/islandora-sandbox?

(Edited to add that https://github.com/dannylamb/islandora-sandbox redirects to https://github.com/Islandora-Devops/islandora-sandbox but presumably `demo/Dockerfile` should be updated anyway.)

**Comment by rosiel** [comment]
Merging #160 will solve some of this, including changing where the composer requirements are defined (https://github.com/Islandora-Devops/islandora_install_profile_demo/blob/main/composer.json). However, there's still a lock file upstream, in the islandora-sandbox, and we need a way to keep that up to date. 

BTW, were you able to recently  use `make demo` to install the old Drupal 8.9 site? I thought that pathway had been broken for a while.

**Comment by kayakr** [comment]
> BTW, were you able to recently use `make demo` to install the old Drupal 8.9 site? I thought that pathway had been broken for a while.

Yes, `make demo` worked for me last night. I manually changed `.env` to specify `TAG=1.0.0-alpha-11`.
 Transcript of buiild attached.
[isle-dc-make-demo-transcript-alpha11-20220210.txt](https://github.com/Islandora-Devops/isle-dc/files/8043634/isle-dc-make-demo-transcript-alpha11-20220210.txt)
I haven't tested much yet. Beyond Drupal core 8.x being unsupported, other modules/versions like Automatic Entity Label, Devel, Entity Embed, Facets, are unsupported or need security updates.

**Comment by joecorall** [comment]
The `make (demo|local)` command has been replaced by documentation.

```
$ make demo
make demo has been removed. To create a demo site, please follow the instructions at https://islandora.github.io/documentation/installation/docker-local/
```
