### ISSUE TITLE
Error loading/viewing node pages (A valid cache entry key is required)

### ISSUE THREAD

**Issue by kspurgin** [Islandora-Devops/isle-dc#212]
This error occurs when you try to load/view a node page. So:

- after you add a new content node via the form and save (when it tries to show you what you just added)
- when you click the title links in the /admin/content view.

In the browser you just see "The website encountered an unexpected error. Please try again later."

In the logs, the error is: 

```
FastCGI sent in stderr: "PHP message: Uncaught PHP Exception InvalidArgumentException: "A valid cache entry key is required. Use getAll() to get all table data." at /var/www/drupal/web/core/modules/views/src/ViewsData.php line 140" while reading response header from upstream
```

Someone also [asked about this on the Islandora-ISLE listserv back in August](https://groups.google.com/g/islandora-isle/c/G_dqcyni2gk). 

I first asked about this yesterday evening [in Slack](https://islandora.slack.com/archives/CM6F4C4VA/p1642036140054600). This report was based on trying to view content nodes created after a bit of mucking around with a new content type that used a new [storage entity type](https://www.drupal.org/project/storage)[^muck].

When I got the error I assumed my mucking around had messed something up.

I tried creating a new Basic page node and a new Article node and they also could not be viewed, but I still assumed I'd messed something up by installing some contrib modules. 

**HOWEVER, I got the same error this morning after doing the following**[^using]: 

- made sure nothing from yesterday was still running in docker
- `docker image prune -a`
- `make clean`
- `cp sample.env .env`
- in .env, changed TAG to 1.0.0-alpha-10 (latest release, as per [Nigel's test on PR204](https://github.com/Islandora-Devops/isle-dc/pull/204#issuecomment-1012187220)
- `make local`

Once the site was up, without changing anything, I created a Basic page node and got the same error. 

Not sure if relevant, but in /admin/reports/status I see: 

```
Errors found
Configuration sync directory
The directory /var/www/drupal/config/sync does not exist.
Trusted Host Settings
Not enabled
The trusted_host_patterns setting is not configured in settings.php. This can lead to security vulnerabilities. It is highly recommended that you configure this. See Protecting against HTTP HOST Header attacks for more information.

Warnings found
Drupal core update status
No update data available
No update information available. Run cron or check manually.
Media
It is potentially insecure to display oEmbed content in a frame that is served from the same domain as your main Drupal site, as this may allow execution of third-party code. You can specify a different domain for serving oEmbed content here.
Search API
The default Drupal core Search module is still enabled. If you are using Search API, you probably want to uninstall the Search module for performance reasons. For more information see the Search API handbook.
```

[^muck]:
    Details of my mucking around, though I don't think they are relevant:
    
    I used commit f8f6bca4293b9a3a02a1840312e3b739060c9c85 (HEAD -> development, origin/development, origin/HEAD)
    
    I ran `make local` without any edits to .env or adding a codebase directory
    
    Before attempting to create any content, I installed and enabled the following modules: 
    
    - drupal/admin_toolbar
    - [drupal/storage](https://www.drupal.org/project/storage)
    - drupal/inline_entity_form

    I then:
    
    - created a test storage entity type (via storage module) containing 2 fields
    - created a new content type that included an entity reference field with my test storage entity type as the target
    - set up my content type form to use inline_entity_form for the entity reference to the storage entity type field
    - set up display of the storage entity type and my content type
    
    THEN I tried creating content and got the error.

[^using]:
    commit f8f6bca4293b9a3a02a1840312e3b739060c9c85 (HEAD -> development, origin/development, origin/HEAD)

**Comment by DonRichards** [comment]
WOW, this one was tricky to automate a fix. :smiley: Also found a simple way to trigger the error as a simplified way to test fixes. Just run `drush cron` should trigger the error every time until the fix is applied. The PR is a working solution. I'd call it a band-aid for now.

**Comment by DonRichards** [comment]
Reviewing the build process log and I see a couple of things that needed attention. Most significantly is the Flysystem module isn't installed via the database import like it does for the `make demo` process.

**Comment by kspurgin** [comment]
RE: Flysystem: this has been an issue with `make local` for a while. There's a separate issue for it still open: #136

**Comment by joecorall** [comment]
The `make local` command has been replaced by documentation.

```
$ make local
make local has been removed. To create a demo site, please follow the instructions at https://islandora.github.io/documentation/installation/docker-local/
```
