### ISSUE TITLE
Refactor Idea

### ISSUE THREAD

**Issue by misilot** [Islandora-Devops/isle-dc#221]
To move the `docker-compose.*.yml` templates used with `make docker-compose.yml` to a sub directory.

Doing this would clean up the root directory and have the singular `docker-compose.yml` that is compiled + a system `docker-compose.override.yml`

**Comment by kstapelfeldt** [comment]
Don thinks this is a good idea (from the tech call).

**Comment by kstapelfeldt** [comment]
@misilot would you be willing to submit a pull request for this?

**Comment by misilot** [comment]
@kstapelfeldt i can take a stab at it. It will probably once I get a working install that I can migrate Config to from an older "tag/branch" of isle-dc

**Comment by misilot** [comment]
@kstapelfeldt would it make sense to move some of the other things into a "build" type of directory as well?

**Comment by kstapelfeldt** [comment]
I must say I don't know, and the meeting is over, but there was general enthusiasm for the direction you are suggesting! You could try the slack channel for more feedback?

**Comment by nigelgbanks** [comment]
Something to add perhaps we could remove the requirement to make the `docker-compose.yml` and instead use 
`COMPOSE_FILE=docker/docker-compose.cantaloup.yml:docker/docker-compose.database.yml:...` in the `.env` file.

**Comment by misilot** [comment]
using the `make -B docker-compose.yml` command has it's advantages that it compiles a single docker-compose.yml that you can use an docker-compose.override.yml with fairly easily. 

You would still have to use `make <somecommand>` if the `docker-compose.yml` isn't being created on the system to have access to the environment variable `COMPOSE_FILE`, and users wouldn't be able to just run arbitrary `docker-compose` commands, unless I am not following what you are suggesting.

**Comment by nigelgbanks** [comment]
@misilot if you have a `.env` file with `COMPOSE_FILE` set you can use `docker compose` commands directly, there isn't a need for the `docker-compose.yml` file in such a case. 

What we would lose is the way that some compose files are included dynamically though settings like `INCLUDE_WATCHTOWER_SERVICE=true`, instead users would have to add the docker file to the list of docker files in `COMPOSE_FILE`, like `COMPOSE_FILE=...:docker-compose.watchtower.yml`

**Comment by misilot** [comment]
Oh, I was thinking of `docker-compose` and not `docker compose`. I am still in `docker-compose` land of thinking. 

Which there are a lot of customization based on flags and the way variables are set, including all the variable interpolations, but if it can be uncomplicated I think that would be great!
