### ISSUE TITLE
Make demo and make local fails if CURDIR has spaces in it

### ISSUE THREAD

**Issue by ysuarez** [Islandora-Devops/isle-dc#235]
I believe that if you have spaces in the path for the isle-dc repo on your system, `make demo` and `make local` will fail.

I was using a path similar to this...

`/home/yamil/isle tests/isle-dc`

This of course leads to Make setting the CURDIR to a path with spaces, and then also leads to the makefile generate-secrets target to run commands that fails since it gets parsed as...

```
docker run --rm -t \
	-v /home/yamil/isle tests/isle-dc/secrets:/secrets \
	-v /home/yamil/isle tests/isle-dc/scripts/generate-secrets.sh:/generate-secrets.sh \
	-w / \
	--entrypoint bash \
	islandora/drupal:1.0.0-alpha-11 -c "/generate-secrets.sh && chown -R `id -u`:`id -g` /secrets"
```
(I was able to see how the commands was parsed by running `make generate-secrets -n`)

On macOS Big Sur and Mojave I got this not too obvious error when running `make demo` or `make local`...

```
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
make: *** [Makefile:285: generate-secrets] Error 125
```

Not sure what is best:
1) to wrap relevant uses of $(CURDIR) in the Makefile with double quotes 
2) OR just make it a requirement that the path to isle-dc repo cannot have paths (with a warning in the docs & README). 
3) OR something else entirely

If folks decide to not change the Makefile code I can create a documentation PR to add a note/tip/warning about not having paths with spaces in the README and/or in the official docs. 

For example, in this page that covers [Installing ISLE Docker Compose ](https://islandora.github.io/documentation/installation/docker-prereq/#installing-isle-docker-compose) and/or the section for [Installing a Demo Server](https://islandora.github.io/documentation/installation/docker-demo/#installing-a-demo-server) 

Thoughts? 

Thanks in advance.

**Comment by ysuarez** [comment]
BTW, if folks want to go with the approach of adding quotes to the use of $(CURDIR) I can create a PR for that change.

**Comment by ysuarez** [comment]
At today's tech call I proposed making a PR that will wrap the use of `$(CURDIR)` in double quotes, so that running make commands work even if the full path to isle-dc has spaces in it.

**Comment by ysuarez** [comment]
@DonRichards  (and others) I have been experimenting with Makefile syntax (I had never used Makefiles this complex before), and wondered what you (all) thought of something.

my original plan was to just wrap the use of $(CURDIR) in double quotes from this...

`-v $(CURDIR)/secrets:/secrets \`

to this...

`-v "$(CURDIR)/secrets":/secrets \`

and I wondered how would you want to handle lines like 332 in the Makefile...

https://github.com/Islandora-Devops/isle-dc/blob/3aa6e1f14374a8f78d2f01f41b22a17eed1bb10a/Makefile#L327-L334

There could be a simple way to handle adding quotes to a snippet that is already in double quotes, but I could not figure it out yet.

For now I took the approach of creating a "[target-specific variable](https://makefiletutorial.com/#target-specific-variables)" called `QUOTED_CURDIR` for getting around the double + double quotes...


https://github.com/Islandora-Devops/isle-dc/blob/431976dfed46c988a325c48b55fd6246b155cbbb/Makefile#L327-L335

I was then able to partially build demo with the changes above while using a path (and thus $CURDIR) to the isle-dc repo with spaces. For example, the demo containers were created. Though I got errors when the makefile tried to call the `drupal-public-files-import: $(SRC)` target, and again the spaces in the path caused errors. 

In this case the error was...

```
make[1]: *** No rule to make target '/TEST/PATH/WITH SPACES', needed by 'drupal-public-files-import'.  Stop.
make[1]: Leaving directory '/TEST/PATH/WITH SPACES'
make: *** [Makefile:314: demo] Error 2
```

Here is the relevant code...


The problem now is that the drupal-public-files-import target's prerequisite is not being matched because of the spaces in the path. It is being seen as multiple files, instead of SRC pointing to a single file.

https://github.com/Islandora-Devops/isle-dc/blob/3aa6e1f14374a8f78d2f01f41b22a17eed1bb10a/Makefile#L226-L231

I am not sure how to fix this, and it will probably take someone with more experience with Makefiles than me.

I am able to wrap `"$(SRC)"` in double quotes in the "recipe/commands" part of the target, and it works fine there in my early tests.

Thoughts?

Thanks in advance.

P.S. In the short term I can create updates to the README and official docs that the path to isle-dc currently cannot have spaces.

**Comment by misilot** [comment]
I believe this is resolved by #237 ?

**Comment by ysuarez** [comment]
In an attempt to be thorough I want to paste a comment that @misilot put in PR #237 

"...
I believe this is limitation with Make per this really old bug report http://savannah.gnu.org/bugs/?712
..."

Based on the info above, If we are running into a limitation of Make, to have spaces in its path, then should I/we revert the parts of my PR #237 that tried to fix this issues incompletely? Then just keep the code that @DonRichards wrote that just stops the Makefile execution with an error if a space is detected in the path? That way we end up with less changes to the resulting Makefile?

**Comment by ysuarez** [comment]
I will close this ticket. @DonRichards  code provides a pretty clear error message for folks that fall into this situation. @misilot thanks for adding more info to this issue.
