### ISSUE TITLE
Clean up .env and change to sample.env instead with README steps

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-dc#24]
- Sample .env - Clean up .env and change to sample.env instead
- add to .gitignore
- Write up steps for how to do this in README

**Comment by g7morris** [comment]
@nikathone Putting your comment from the PR here https://github.com/Islandora-Devops/isle-dc/pull/6#issuecomment-614146082 so we don't loose sight of it and if you also want to work on this.

"For the sample.env I did update the docker-compose.yml accordingly but only focused on drupal and the mariadb services. The other services are using env-file which point to .env and that doesn't make it easier to know which environment variables they really need. It could be easier for someone who understand how these services work to do the refactoring."

You had one more good comment here https://github.com/Islandora-Devops/isle-dc/pull/6#issuecomment-614147216

"One more thing once we have the sample.env and docker-compose.yml environment variables setup we should then get rid of .env, add it to .gitignore and then update the doc."

**Comment by nikathone** [comment]
Ok. will wait for the merge to see if I can take a stab at this again.
