### ISSUE TITLE
make demo fails with Access denied for user 'root'@'isle-dc_drupal_1.isle-dc_default'

### ISSUE THREAD

**Issue by kayakr** [Islandora-Devops/isle-dc#240]
isle-dc on `3e77d34` commit, vanilla `.env`, MacOS:
```
Waiting for up to 300 seconds to connect to Database mariadb:3306
Waiting for 3306 on mariadb to open.
Database found
Validating Database credentials
Credentials are valid
ERROR 1045 (28000): Access denied for user 'root'@'isle-dc_drupal_1.isle-dc_default' (using password: YES)
make[1]: *** [drupal-database] Error 1
make: *** [demo] Error 2
```

**Comment by kayakr** [comment]
Try changing `.env` to `USE_SECRETS=false`, `make demo` gets a little further then prompts for a password but it's not clear what component is asking for credentials or which credentials to supply...

```
isle-dc_blazegraph_1 is up-to-date
Recreating isle-dc_homarus_1 ... 
Recreating isle-dc_recast_1  ... 
isle-dc_solr_1 is up-to-date
Recreating isle-dc_hypercube_1 ... 
Recreating isle-dc_homarus_1    ... done
Recreating isle-dc_recast_1     ... done
Recreating isle-dc_hypercube_1  ... done
Recreating isle-dc_cantaloupe_1 ... done
Recreating isle-dc_milliner_1   ... done
Recreating isle-dc_alpaca_1     ... done
Recreating isle-dc_activemq_1   ... done
Recreating isle-dc_houdini_1    ... done
Recreating isle-dc_mariadb_1    ... done
Recreating isle-dc_matomo_1     ... done
Recreating isle-dc_fcrepo_1     ... done
Recreating isle-dc_drupal_1     ... done
PHP Notice:  Uninitialized string offset: 0 in /var/www/drupal/vendor/drush/drush/src/Preflight/ArgsPreprocessor.php on line 72
PHP Notice:  Uninitialized string offset: 0 in /var/www/drupal/vendor/drush/drush/src/Preflight/ArgsPreprocessor.php on line 72
PHP Notice:  Uninitialized string offset: 0 in /var/www/drupal/vendor/drush/drush/src/Preflight/ArgsPreprocessor.php on line 72
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
sudo: 3 incorrect password attempts
make[1]: *** [update-settings-php] Error 1
make: *** [demo] Error 2
```

**Comment by kayakr** [comment]
Looks like local user password was needed prior to 
`docker cp "{redacted}/projects/isle-dc/demo-data/public-files.tgz" $(docker-compose ps -q drupal):/tmp/public-files.tgz`

**Comment by kayakr** [comment]
`make demo` just ends after 
`Action processing results: Emit a media event to a queue/topic (121).`
It doesn't announce that make is completed or what URL to visit.

Tried to login to https://islandora.traefik.me/ using 'admin' and 'password' but rejected. Used `docker-compose exec -T drupal with-contenv bash -lc 'drush --root /var/www/drupal/web uli 1'` instead.

- [x] docs need updating now `make demo` doesn't work ootb.
- [ ] docs should mention local password may be required
- [ ] Are non-secrets mode Drupal credentials really admin:password?
- [ ] `make demo` should announce successful completion

**Comment by rosiel** [comment]
Unfortunately it is my belief that the "demo box on docker hub" which is used by `make demo` was clobbered over with the "demo box on docker hub" which was meant for `make demo-install-profile`. So you're probably getting the install profile box but trying to run some commands that don't work.

The documentation hasn't been updated in part because the install profile pull request on isle-dc is still open. But this seems broken enough that an update is warranted.

There's a "discussion" about what options should do, here: https://github.com/Islandora/documentation/discussions/2037 

And yes, it really is/was "admin/password" 🥺

**Comment by noahwsmith** [comment]
@nigelgbanks can you comment on Rosie's assessment, please?

**Comment by noahwsmith** [comment]
Oh, and Willow re-tested #160 again this week - we're ready to sign off on that. Me/Don/Danny are the primary authors. Do we need someone else to hit the merge button, now that Willow is on our team too?

**Comment by rosiel** [comment]
Documentation updated: https://github.com/Islandora/documentation/blob/main/docs/installation/docker-demo.md

**Comment by noahwsmith** [comment]
Beautiful! Thanks Rosie!

**Comment by joecorall** [comment]
This sounds like it may have been closed already but the `make demo` command has been replaced by documentation.

```
$ make demo
make demo has been removed. To create a demo site, please follow the instructions at https://islandora.github.io/documentation/installation/docker-local/
```
