### ISSUE TITLE
Update Make file for use again once build is working post-merge

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-dc#26]
* Review Makefile again once we get build working with MVP3 and 2 merged. 

* Ensure that value of `docker_compose_project ?= ` can be changed from hard-coded islandora to match .env value instead otherwise it appears Docker volumes and container names don't match and cause issues

* Review @nigelgbanks 's suggestion here https://github.com/Islandora-Devops/isle-dc/pull/6#discussion_r409754101 re `Minor non-issue. Should be added to .PHONY targets.`

* Update README or documentation with syntax in Make file, benefits of using and scripts / actions it assumes.

**Comment by noahwsmith** [comment]
Sounds like this is in progress from other people. I was going to add this

```
jwt_keys:
	scripts/generate_jwt_keys.sh
```

but I'll hand this back as I don't have much other input.

**Comment by g7morris** [comment]
@nikathone I'd like to assign this to you for testing again post-merge please.

**Comment by nikathone** [comment]
@g7morris sure. I should be able to test it before the end of the week.

**Comment by g7morris** [comment]
@nikathone During the course of your testing, can you review https://github.com/Islandora-Devops/isle-dc/pull/6 specifically @nigelgbanks 's recommendation for a fix https://github.com/Islandora-Devops/isle-dc/pull/6#discussion_r409754101 

The issue is that the Docker Compose project name doesn't match the Makefile

From that PR:

> Is this partially due to line 5 in the Makefile? docker_compose_project ?= islandora
> 
> [Followup] interesting. I replaced islandora with docker_compose_project ?= isle_dc_proto2b on line 5 and got make: *** [Makefile:23: up] Error 1
