### ISSUE TITLE
allow HTTP-only mode

### ISSUE THREAD

**Issue by rbos** [Islandora-Devops/isle-dc#268]
Our infrastructure has a lot of VMs behind a load-balancer, and our IT policy requires that SSL certs be handled on the LB.

Is it possible to force ISLE to use only HTTP on port 80? It is not obvious how to set that up.

**Comment by DonRichards** [comment]
Pointing to the Slack discussion on this https://islandora.slack.com/archives/C019U12D44Q/p1656345103603689

I think Tom's suggestion of removing Trafik's redirect should be all that's needed to get it to work correctly. I have not tested this.

**Comment by rbos** [comment]
It didn't seem to work when I tried it (I was the one in the Slack discussion), but maybe I did something wrong. Can you amplify on what lines exactly I should remove?

**Comment by rosiel** [comment]
Have you had any luck with this since your last comment?

**Comment by rbos** [comment]
Sorry, haven't had much time to look at it between other projects. It's a bit low on the list at the moment.

**Comment by rbos** [comment]
This kills all redirects and forces it to listen only on port 80. Figured it out ages ago. It should still be a configuration option, but this hack does the trick.

```
# kill the redirect and listen from port 443, use 80 entirely
cd /opt/isle-dc/build/docker-compose/;
grep -l redirectscheme * | while read i; do sed -i /redirectscheme/d $i;done
grep -l :443 * | while read i; do sed -i /:443/d $i;done
```
