### ISSUE TITLE
`make local` fails, The profile islandora_install_profile_demo does not exist.

### ISSUE THREAD

**Issue by rosiel** [Islandora-Devops/isle-dc#280]
On commit `8cc8f02e085fa0c2033eb314baffc1611716c376` using `make local`,  the build fails:

```
 [notice] Starting Drupal installation. This takes a while.

In ExtensionList.php line 522:
                                                              
  The profile islandora_install_profile_demo does not exist.  

```

**Comment by DonRichards** [comment]
Should have been addressed with this https://github.com/Islandora-Devops/isle-dc/commit/9b9c20c1425430623070448ab52960414aec4d5c

**Comment by rosiel** [comment]
as i mentioned, i was on a much later commit.

The problem was i had stuff in my codebase folder.

**Comment by kayakr** [comment]
I'm getting this error using `make local`. https://github.com/Islandora-Devops/isle-dc/blob/development/Makefile#L153 refers to `islandora_install_profile_demo` and AFAICT .env `DRUPAL_INSTALL_PROFILE` is not referenced anywhere in the Makefile, so setting the value in .env will have no effect.

**Comment by joecorall** [comment]
The `make local` command has been replaced by documentation.

```
$ make local
make local has been removed. To create a demo site, please follow the instructions at https://islandora.github.io/documentation/installation/docker-local/
```
