### ISSUE TITLE
[META ISSUE] Set up ISLE-DC with [integration?] testing

### ISSUE THREAD

**Issue by rosiel** [Islandora-Devops/isle-dc#293]
It would be easier to make contributions to ISLE-DC if it included tests that ensured things are working properly. 

** Please flesh out this issue with what kinds of tests etc**

Related: #238 
Sister issue for Playbook: https://github.com/Islandora-Devops/islandora-playbook/issues/231

**Comment by joecorall** [comment]
Does https://github.com/Islandora-Devops/isle-dc/pull/384 close this issue?

**Comment by rosiel** [comment]
Probably.
