### ISSUE TITLE
[DOCUMENTATION] README should be clear what services are exposed by default

### ISSUE THREAD

**Issue by rosiel** [Islandora-Devops/isle-dc#296]
The README outlines, for a demo site (though by implication for all sites unless configured otherwise) where to access various services, including Fedora, Blazegraph, Solr, etc. However [not all these services are exposed anymore](https://github.com/Islandora-Devops/isle-dc/issues/292). The README should be updated to reflect the new availability status of various services out of the box, and the new options for exposing them.

**Comment by DonRichards** [comment]
Some updates added via the PR https://github.com/Islandora-Devops/isle-dc/pull/304/files
