### ISSUE TITLE
Tesseract in Hypercube does not support  JP2 files 

### ISSUE THREAD

**Issue by alxp** [Islandora-Devops/isle-dc#298]
This was a side-issue that I found while investigating  https://github.com/Islandora/islandora/issues/903

Steps to reproduce:

On fresh install of ISLE-DC development branch as of 2022-10-17:

1. Create an object with model Page
2. Add a Media of type File and upload a TIFF file, checking 'Original File' in Media Use.
3. Add an object with model Page
4. Add a Media of type File and upload a JP2 file, checking 'Original File' in Media Use.

## Expected behaviour:

Both objects should have an Extracted Text media containing the text embedded in the respective images.

## Actual result:

The media with a TIFF file has thumbnail, service file, FITS file and Extracted Text
The media with the JP2 has thumbnail, service file and FITS file but no Extracted Text.

This error shows up in the Hypercube logs:

```bash
[2022-10-18 15:00:35] crayfish.cmd_execute_service.ERROR: Process exited with non-zero code. {"exit_code":1,"stderr":"Error in pixReadMemJp2k: function not present\nError in pixReadMem: jp2k: no pix returned\nError during processing.\n"} []
```

**Comment by nigelgbanks** [comment]
Fixed in https://github.com/Islandora-Devops/isle-buildkit/pull/238
