### ISSUE TITLE
Solr does not work on `starter` or `starter_dev`

### ISSUE THREAD

**Issue by rosiel** [Islandora-Devops/isle-dc#305]
The Solr URL configuration is not being set. 

It appears to be because the [lines that do this are skipped when you're not using Islandora Defaults](url).

As far as I can tell, the call stack is:
`make starter_dev` (or `starter`) calls (`make`) `hydrate`
`make hydrate` calls (`make`) `update-config-from-environment`
`make update-config-from-environment` calls `configure_islandora_default_module` which is a function available in the Drupal container, presumably copied from `isle-buildkit/drupal/rootfs/etc/islandora/utilities.sh`
`isle-buildkit/drupal/rootfs/etc/islandora/utilities.sh`'s `configure_islandora_default_module` does the Solr URL config. 

Is the solution as simple as moving those lines to the function below, [`configure_search_api_solr_module`](https://github.com/Islandora-Devops/isle-buildkit/blob/main/drupal/rootfs/etc/islandora/utilities.sh#L447-L458)?

@seth-shaw-asu @adam-vessey

**Comment by seth-shaw-asu** [comment]
Yeah, it appears that configure_islandora_defaults _currently_ only sets search_api. Its actions can probably be rolled into configure_search_api_solr_module.

**Comment by adam-vessey** [comment]
Half-tempted to suggest making things more atomic, splitting up the functions between enabling and configuring things, as with the `--existing-config` it's somewhat expected that there should be no other modules enabled.

... really, might be nice to avoid changing the configuration proper with provisioned/environment specifics (as in, that which is imported/exported) in all cases by using [Drupal's configuration override mechanism](https://www.drupal.org/docs/drupal-apis/configuration-api/configuration-override-system).

**Comment by rosiel** [comment]
I'm gonna make a new issue for the "avoid changes to configuration" thing.

**Comment by seth-shaw-asu** [comment]
@rosiel, okay to close with the merged PR?

**Comment by rosiel** [comment]
Nope. Needs

- [x] Buildkit release (automatically deploys?)
- [x] PR on ISLE-DC to use the new release

**Comment by rosiel** [comment]
relevant PR: https://github.com/Islandora-Devops/isle-dc/pull/308
