### ISSUE TITLE
make demo fails 

### ISSUE THREAD

**Issue by DanRoller** [Islandora-Devops/isle-dc#313]
Tried **make demo** multiple times which all failed, but **make local** works.
Local is good enough for me but others may need make demo.

No changes made to folder after downloading isle-dc-development.
On Windows WSL, this weekend, the error was

make demo
...
**Installed /usr/local/lib/python3.11/site-packages/certifi-2022.9.24-py3.11.egg
error: urllib3 2.0.0a1 is installed but urllib3<1.27,>=1.21.1 is required by {'requests'}**
make[1]: *** [Makefile:384: demo_content] Error 1
make[1]: Leaving directory '/home/dan/isle-dc-development'
make: *** [Makefile:342: demo] Error 2

**Comment by DonRichards** [comment]
There was an issue with the python version and library changes that was corrected yesterday. To fix it locally, remove the **islandora_workbench/** directory or run `git pull` from within the **islandora_workbench/** directory.

**Comment by DanRoller** [comment]
Demo now works!  As a newbe it helps to see some test data as I hadn't yet gotten it together to ingest into the make local.
Thanks

Historical note: Pre-Covid, when our history museum was deciding on direction, I tried to install Islandora 8 and failed at every possible install method over weeks.  The focus turned to Archivesspace, with that in place, I'm back on to Islandora.
  
This time make demo failed, and now is fixed - quickly and make local worked, first time.

I am amazed at the progress Isle/DC has made.

**Comment by DonRichards** [comment]
Thanks @DanRoller, for reporting this.
