### ISSUE TITLE
Question about set-files-owner

### ISSUE THREAD

**Issue by noahwsmith** [Islandora-Devops/isle-dc#317]
Currently the code is `sudo find "$(SRC)" -exec chown $(shell id -u):101 {} \;`

What is the advantage of doing that vs doing `sudo chown -R $(shell id -u):101 $(SRC)`

https://github.com/Islandora-Devops/isle-dc/blob/development/Makefile#L127

The current execution takes a REALLY long time because of the way it goes through each file individually rather than just using the recursive flag on the `chown` command. Any objections to switching to the faster way of doing this?

**Comment by nigelgbanks** [comment]
They should be equivalent as far as I know

**Comment by noahwsmith** [comment]
PR available for testing ^
