### ISSUE TITLE
Changes needed for "make demo" to finish.

### ISSUE THREAD

**Issue by bdgregg** [Islandora-Devops/isle-dc#328]
https://github.com/Islandora-Devops/isle-dc/blob/3261fc9223350aa443b4ea7bfc702ab69636d1de/Makefile#L381

In the line referenced there seem to be two issues to note:

1. The example_content.yml file coming from https://github.com/DonRichards/islandora_workbench_demo_content has changed from instead of finding and replacing '^nopassword' to simply '^password'.  This change happened recently.
2. To properly execute the shell command in sed it seems that we need to enclose the $(shell ... _PASSWORD) in single quotes to allow the execution of pulling the DRUPAL_DEFAULT_ACCOUNT_PASSWORD from the file.  Otherwise the line to perform a docker run fails to execute due to an invalid password.

Our changes that made "make demo" work as expected:
From:
`$(SED_DASH_I) 's/^nopassword.*/password\: $(shell cat secrets/live/DRUPAL_DEFAULT_ACCOUNT_PASSWORD) /g' islandora_workbench/islandora_workbench_demo_content/example_content.yml`
To:
`$(SED_DASH_I) 's/^password.*/password\: '$(shell cat secrets/live/DRUPAL_DEFAULT_ACCOUNT_PASSWORD)' /g' islandora_workbench/islandora_workbench_demo_content/example_content.yml`

Hope this helps.

**Comment by ctgraham** [comment]
Note that if `secrets/live/DRUPAL_DEFAULT_ACCOUNT_PASSWORD` contains a slash, this will break the `sed` command.  I also think that slash on the colon after RHS "password" may be spurious.
