### ISSUE TITLE
demo_content does not honor chosen domain name

### ISSUE THREAD

**Issue by ctgraham** [Islandora-Devops/isle-dc#331]
The `demo_content` subcommand does not utilize the `DOMAIN` variable if edited from the default of "islandora.traefik.me".

Steps to reproduce:
```
sed -i "s/^DOMAIN=islandora.traefik.me/DOMAIN=$HOSTNAME/" sample.env
make demo
```

Error message:
```
...
cd islandora_workbench && docker run -it --rm --network="host" -v "/opt/isle-dc"/islandora_workbench:/workbench --name my-running-workbench workbench-docker bash -lc "./workbench --config /workbench/islandora_workbench_demo_content/example_content.yml"
Error: Content type islandora_object does not exist on https://islandora.traefik.me.

make[1]: *** [Makefile:478: demo_content] Error 1
make[1]: Leaving directory '/opt/isle-dc'
make: *** [Makefile:133: demo] Error 2
```

Proposed resolution:
`sed` the "host" value in `islandora_workbench/islandora_workbench_demo_content/example_content.yml`.

**Comment by DonRichards** [comment]
PR https://github.com/Islandora-Devops/isle-dc/pull/334

**Comment by joecorall** [comment]
https://github.com/Islandora-Devops/isle-dc/pull/334 merged so closing this issue
