### ISSUE TITLE
The drupal.Dockerfile still using registry.gitlab.com/nikathone/drupal-docker-good-defaults/php-nginx:latest for php and nginx base image

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-dc#34]
Per @nikathone's comment here https://github.com/Islandora-Devops/isle-dc/pull/6

"The drupal.Dockerfile still using registry.gitlab.com/nikathone/drupal-docker-good-defaults/php-nginx:latest for php and nginx base image but this will change once we have a CI to build images/nginx-php/Dockerfile."

@nikathone Can we make an official Islandora version of this post-merge? We now have control over the Islandora Dockerhub account to be able to push images. We can also make a new repo accordingly if need be too. Your thoughts?

**Comment by g7morris** [comment]
@dannylamb Have you made a new Github repo and Dockerhub image from this?

**Comment by dannylamb** [comment]
Yeah, I can update that.  I'm rocking the new repo now in my fork and everything works fine.
