### ISSUE TITLE
make reindex-triplestore failing

### ISSUE THREAD

**Issue by joshdentremont** [Islandora-Devops/isle-dc#344]
I was testing some make commands and noticed that the triplestore reindex command is failing with the following:
```
docker-compose exec -T drupal with-contenv bash -lc 'drush --root /var/www/drupal/web -l ${DRUPAL_DEFAULT_SITE_URL} vbo-exec all_taxonomy_terms emit_term_event --configuration="queue=islandora-indexing-triplestore-index&event=Update"'

  Command "vbo-exec" is not defined.

make: *** [reindex-triplestore] Error 1
```

**Comment by aOelschlager** [comment]
I think that's a drush command from the [views bulk operations ](https://git.drupalcode.org/project/views_bulk_operations/-/blob/4.2.x/src/Commands/ViewsBulkOperationsCommands.php#L106)module. It might not be installed/enabled.

**Comment by joshdentremont** [comment]
Thanks. I just put in a PR to update the docs to reflect this: https://github.com/Islandora/documentation/pull/2239
