### ISSUE TITLE
Make starter_dev fails to build

### ISSUE THREAD

**Issue by DonRichards** [Islandora-Devops/isle-dc#354]
Composer.lock looks like it's out of date and needs to be updated for the islandora-starter-site
```
docker compose exec -T drupal with-contenv bash -lc 'composer install'
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - chi-teck/drupal-code-generator is locked to version 3.1.0 and an update of this package was not requested.
    - chi-teck/drupal-code-generator 3.1.0 requires php >=8.1.0 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 2
    - consolidation/log is locked to version 3.0.0 and an update of this package was not requested.
    - consolidation/log 3.0.0 requires php >=8.0.0 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 3
    - consolidation/robo is locked to version 4.0.6 and an update of this package was not requested.
    - consolidation/robo 4.0.6 requires php >=8.0 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 4
    - consolidation/site-process is locked to version 5.2.0 and an update of this package was not requested.
    - consolidation/site-process 5.2.0 requires php >=8.0.14 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 5
    - drupal/core is locked to version 10.1.2 and an update of this package was not requested.
    - drupal/core 10.1.2 requires composer-runtime-api ^2.1 -> found composer-runtime-api[2.0.0] but it does not match the constraint.
  Problem 6
    - drupal/flysystem is locked to version 2.1.0-rc5 and an update of this package was not requested.
    - drupal/flysystem 2.1.0-rc5 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 7
    - drush/drush is locked to version 12.1.2 and an update of this package was not requested.
    - drush/drush 12.1.2 requires composer-runtime-api ^2.2 -> found composer-runtime-api[2.0.0] but it does not match the constraint.
  Problem 8
    - egulias/email-validator is locked to version 4.0.1 and an update of this package was not requested.
    - egulias/email-validator 4.0.1 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 9
    - grasmash/expander is locked to version 3.0.0 and an update of this package was not requested.
    - grasmash/expander 3.0.0 requires php >=8.0 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 10
    - grasmash/yaml-cli is locked to version 3.1.0 and an update of this package was not requested.
    - grasmash/yaml-cli 3.1.0 requires php >=8.0 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 11
    - laminas/laminas-stdlib is locked to version 3.17.0 and an update of this package was not requested.
    - laminas/laminas-stdlib 3.17.0 requires php ~8.1.0 || ~8.2.0 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 12
    - league/csv is locked to version 9.9.0 and an update of this package was not requested.
    - league/csv 9.9.0 requires php ^8.1.2 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 13
    - maennchen/zipstream-php is locked to version 3.1.0 and an update of this package was not requested.
    - maennchen/zipstream-php 3.1.0 requires php-64bit ^8.1 -> your php-64bit version (7.4.33) does not satisfy that requirement.
  Problem 14
    - phootwork/collection is locked to version v3.2.2 and an update of this package was not requested.
    - phootwork/collection v3.2.2 requires php >=8.0 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 15
    - phootwork/lang is locked to version v3.2.2 and an update of this package was not requested.
    - phootwork/lang v3.2.2 requires php >=8.0 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 16
    - phpowermove/docblock is locked to version v4.0 and an update of this package was not requested.
    - phpowermove/docblock v4.0 requires php >=8.0 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 17
    - psr/cache is locked to version 3.0.0 and an update of this package was not requested.
    - psr/cache 3.0.0 requires php >=8.0.0 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 18
    - psr/log is locked to version 3.0.0 and an update of this package was not requested.
    - psr/log 3.0.0 requires php >=8.0.0 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 19
    - symfony/console is locked to version v6.3.2 and an update of this package was not requested.
    - symfony/console v6.3.2 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 20
    - symfony/dependency-injection is locked to version v6.3.2 and an update of this package was not requested.
    - symfony/dependency-injection v6.3.2 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 21
    - symfony/deprecation-contracts is locked to version v3.3.0 and an update of this package was not requested.
    - symfony/deprecation-contracts v3.3.0 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 22
    - symfony/error-handler is locked to version v6.3.2 and an update of this package was not requested.
    - symfony/error-handler v6.3.2 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 23
    - symfony/event-dispatcher is locked to version v6.3.2 and an update of this package was not requested.
    - symfony/event-dispatcher v6.3.2 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 24
    - symfony/event-dispatcher-contracts is locked to version v3.3.0 and an update of this package was not requested.
    - symfony/event-dispatcher-contracts v3.3.0 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 25
    - symfony/filesystem is locked to version v6.3.1 and an update of this package was not requested.
    - symfony/filesystem v6.3.1 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 26
    - symfony/finder is locked to version v6.3.3 and an update of this package was not requested.
    - symfony/finder v6.3.3 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 27
    - symfony/http-foundation is locked to version v6.3.2 and an update of this package was not requested.
    - symfony/http-foundation v6.3.2 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 28
    - symfony/http-kernel is locked to version v6.3.3 and an update of this package was not requested.
    - symfony/http-kernel v6.3.3 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 29
    - symfony/mime is locked to version v6.3.3 and an update of this package was not requested.
    - symfony/mime v6.3.3 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 30
    - symfony/process is locked to version v6.3.2 and an update of this package was not requested.
    - symfony/process v6.3.2 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 31
    - symfony/routing is locked to version v6.3.3 and an update of this package was not requested.
    - symfony/routing v6.3.3 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 32
    - symfony/serializer is locked to version v6.3.3 and an update of this package was not requested.
    - symfony/serializer v6.3.3 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 33
    - symfony/service-contracts is locked to version v3.3.0 and an update of this package was not requested.
    - symfony/service-contracts v3.3.0 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 34
    - symfony/string is locked to version v6.3.2 and an update of this package was not requested.
    - symfony/string v6.3.2 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 35
    - symfony/translation is locked to version v6.3.3 and an update of this package was not requested.
    - symfony/translation v6.3.3 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 36
    - symfony/translation-contracts is locked to version v3.3.0 and an update of this package was not requested.
    - symfony/translation-contracts v3.3.0 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 37
    - symfony/validator is locked to version v6.3.2 and an update of this package was not requested.
    - symfony/validator v6.3.2 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 38
    - symfony/var-dumper is locked to version v6.3.3 and an update of this package was not requested.
    - symfony/var-dumper v6.3.3 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 39
    - symfony/var-exporter is locked to version v6.3.2 and an update of this package was not requested.
    - symfony/var-exporter v6.3.2 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 40
    - symfony/yaml is locked to version v6.3.3 and an update of this package was not requested.
    - symfony/yaml v6.3.3 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 41
    - doctrine/event-manager is locked to version 2.0.0 and an update of this package was not requested.
    - doctrine/event-manager 2.0.0 requires php ^8.1 -> your php version (7.4.33) does not satisfy that requirement.
  Problem 42
    - symfony/http-foundation v6.3.2 requires php >=8.1 -> your php version (7.4.33) does not satisfy that requirement.
    - drupal/core-recommended 10.1.2 requires symfony/http-foundation ~v6.3.0 -> satisfiable by symfony/http-foundation[v6.3.2].
    - drupal/core-recommended is locked to version 10.1.2 and an update of this package was not requested.

make: *** [starter_dev] Error 2
```

Related to https://github.com/Islandora-Devops/islandora-starter-site/issues/109

**Comment by Natkeeran** [comment]
I ran into the same issue.

**Comment by aOelschlager** [comment]
The tag in the .env file is for images running php7 and starter site needs to run now on php8 because of drupal 10. These two prs #346 #347 need to be merged and then the tag in the .env file needs to be changed from 1.0.10 to main. Might still have issues with drush 12 and drupal 10 specific to the isle-dc install but you will get a working site (I was able to after I made those changes locally.)

**Comment by aOelschlager** [comment]
Drupal 10 with Drush 12 issues I mentioned in last comment during make starter_dev:

docker compose exec -T drupal with-contenv bash -lc 'chown -R nginx:nginx .'
make drupal-database
make[1]: Entering directory '/path/to/isle-dc'
Waiting for up to 300 seconds to connect to Database mariadb:3306
Waiting for 3306 on mariadb to open.
Database found
Validating Database credentials
mysqld is alive
Credentials are valid
make[1]: Leaving directory '/path/to/isle-dc'
make update-settings-php
make[1]: Entering directory '/path/to/isle-dc'
PHP Fatal error:  Uncaught Error: Undefined constant Symfony\Component\HttpFoundation\Request::HEADER_X_FORWARDED_ALL in /usr/share/drush/Commands/UpdateSettingsCommands.php:204
Stack trace:
#0 [internal function]: Drush\Commands\UpdateSettingsCommands->setReverseProxySettings()
#1 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array()
#2 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
#3 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#4 /var/www/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(391): Consolidation\AnnotatedCommand\CommandProcessor->process()
#5 /var/www/drupal/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#6 /var/www/drupal/vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run()
#7 /var/www/drupal/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/drupal/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#9 /var/www/drupal/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run()
#10 /var/www/drupal/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
#11 /var/www/drupal/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run()
#12 /var/www/drupal/vendor/drush/drush/drush(4): require('/var/www/drupal...')
#13 /var/www/drupal/vendor/bin/drush(120): include('/var/www/drupal...')
#14 {main}
  thrown in /usr/share/drush/Commands/UpdateSettingsCommands.php on line 204
 [warning] Drush command terminated abnormally.
make[1]: Leaving directory '/path/to/isle-dc'
docker compose exec -T drupal with-contenv bash -lc "drush si -y --existing-config minimal --account-pass password"
 You are about to:
 * DROP all tables in your 'drupal_default' database.

 // Do you want to continue?: yes.                                              

 [notice] Starting Drupal installation. This takes a while.
 [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile
 [notice] Performed install task: install_verify_requirements
 [notice] Performed install task: install_verify_database_ready
 [notice] Performed install task: install_base_system
 [notice] Performed install task: install_bootstrap_full
 [error]  The Flysystem driver is missing. 
 [warning] Could not find required jsonld.settings to add default RDF namespaces.
 [warning] The "advanced_search_result_pager:solr_search_content__page_1" was not found
 [warning] The "advanced_search_result_pager:solr_search_content__block_1" was not found
 [warning] The "advanced_search_block:solr_search_content__page_1" was not found
 [warning] The "advanced_search_block:solr_search_content__block_1" was not found
 [notice] Performed install task: install_config_import_batch
 [notice] Performed install task: install_config_download_translations
 [notice] Performed install task: install_config_revert_install_changes
 [notice] Performed install task: install_configure_form
 [notice] Performed install task: install_finished
 [success] Installation complete.
docker compose exec -T drupal with-contenv bash -lc "drush -l https://islandora.traefik.me user:role:add fedoraadmin admin"
 [success] Added fedoraadmin role to admin
MIGRATE_IMPORT_USER_OPTION=--userid=1 make hydrate
make[1]: Entering directory '/path/to/isle-dc'
PHP Fatal error:  Uncaught Error: Undefined constant Symfony\Component\HttpFoundation\Request::HEADER_X_FORWARDED_ALL in /usr/share/drush/Commands/UpdateSettingsCommands.php:204
Stack trace:
#0 [internal function]: Drush\Commands\UpdateSettingsCommands->setReverseProxySettings()
#1 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array()
#2 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
#3 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#4 /var/www/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(391): Consolidation\AnnotatedCommand\CommandProcessor->process()
#5 /var/www/drupal/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#6 /var/www/drupal/vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run()
#7 /var/www/drupal/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/drupal/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun()
#9 /var/www/drupal/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run()
#10 /var/www/drupal/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
#11 /var/www/drupal/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run()
#12 /var/www/drupal/vendor/drush/drush/drush(4): require('/var/www/drupal...')
#13 /var/www/drupal/vendor/bin/drush(120): include('/var/www/drupal...')
#14 {main}
  thrown in /usr/share/drush/Commands/UpdateSettingsCommands.php on line 204
 [warning] Drush command terminated abnormally.
 [notice] Already enabled: islandora_core_feature

 // Do you want to update remove_jsonld_format key in jsonld.settings config?:  
 // yes.                                                                        


 // Do you want to update broker_url key in islandora.settings config?: yes.    

Fedora Admin role already exists.  No need to create it.
 [success] Added fedoraadmin role to admin
 [notice] Already enabled: jwt
+------------+---------------------------+-----------+
| Collection | Config                    | Operation |
+------------+---------------------------+-----------+
|            | key.key.islandora_rsa_key | Update    |
+------------+---------------------------+-----------+

 // Import the listed configuration changes?: yes.                              

 [notice] Synchronized configuration: update key.key.islandora_rsa_key.
 [notice] Finalizing configuration synchronization.
 [success] The configuration was imported successfully.

                                       
  The "--pipe" option does not exist.  
                                       

Search API is not installed.  Skipping configuration
 [notice] Already enabled: search_api_solr

In PmCommands.php line 177:
                                                                               
  The following module(s) are not installed: search. No modules to uninstall.  
                                                                               

make[1]: [Makefile:160: update-config-from-environment] Error 1 (ignored)

                                       
  The "--pipe" option does not exist.  
                                       

matomo is not installed.  Skipping configuration

                                       
  The "--pipe" option does not exist.  
                                       

openseadragon is not installed.  Skipping configuration

                                       
  The "--pipe" option does not exist.  
                                       

Search API is not installed.  Skipping configuration

                                       
  The "--pipe" option does not exist.  
                                       

search_api_solr is not installed.  Skipping core setup.
Waiting for 8080 on blazegraph to open.
Triplestore Found at blazegraph:8080
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   736  100    18  100   718    131   5242 --:--:-- --:--:-- --:--:--  5411
CREATED: islandora  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   282  100    60  100   222     74    274 --:--:-- --:--:-- --:--:--   349
<?xml version="1.0"?><data modified="2" milliseconds="800"/>
  1/35 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   2%
  4/35 [▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░]  11%
  7/35 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  20%
 11/35 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  31%
 14/35 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  40%
 18/35 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  51%
 21/35 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░]  60%
 25/35 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░]  71%
 28/35 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░]  80%
 32/35 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░]  91%
 35/35 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 [notice] Processed 35 items (35 created, 0 updated, 0 failed, 0 ignored) in 2 seconds (1065.1/min) - done with 'islandora_defaults_tags'

  1/18 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   5%
  2/18 [▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░]  11%
  4/18 [▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░]  22%
  6/18 [▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░]  33%
  8/18 [▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░]  44%
  9/18 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  50%
 11/18 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░]  61%
 13/18 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░]  72%
 15/18 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░]  83%
 17/18 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░]  94%
 18/18 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 [notice] Processed 18 items (18 created, 0 updated, 0 failed, 0 ignored) in 0.9 seconds (1265.7/min) - done with 'islandora_tags'
 [error]  http://islandora.traefik.me:8081/fcrepo/rest/ is unavailable, cannot connect. 
 [success] Cache rebuild complete.
make[1]: Leaving directory '/path/to/isle-dc'
docker compose exec -T drupal with-contenv bash -lc 'drush -l https://islandora.traefik.me migrate:import --userid=1 islandora_fits_tags'
 [notice] Now acting as user ID 1

 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 [notice] Processed 1 item (1 created, 0 updated, 0 failed, 0 ignored) in 0.2 seconds (260.2/min) - done with 'islandora_fits_tags'
 [notice] Switching back from user 1.
#docker compose exec -T drupal with-contenv bash -lc 'chown -R `id -u`:nginx /var/www/drupal'
#docker compose exec -T drupal with-contenv bash -lc 'drush migrate:rollback islandora_defaults_tags,islandora_tags'
make login
make[1]: Entering directory '/path/to/isle-dc'


/=========== LOGIN ===========
http://islandora.traefik.me/user/reset/1/1693420546/pQz45vZXu4op3DHr5qptGRH-x9FUgkY45GH1oqCNKQQ/login
/=============================

make[1]: Leaving directory '/path/to/isle-dc'

**Comment by aOelschlager** [comment]
This error:
PHP Fatal error: Uncaught Error: Undefined constant Symfony\Component\HttpFoundation 
Is related to this: https://github.com/Islandora-Devops/isle-site-template/pull/7
Maybe a fix should go here: https://github.com/Islandora-Devops/isle-buildkit/blob/main/drupal/rootfs/usr/share/drush/Commands/UpdateSettingsCommands.php#L204

**Comment by aOelschlager** [comment]
The pipe error comes from a call to this function:
https://github.com/Islandora-Devops/isle-dc/blob/development/Makefile#L599
These are the places where pipe is being used and match my errors posted above: https://github.com/search?q=repo%3AIslandora-Devops%2Fisle-buildkit%20--pipe&type=code

It doesn't look like the pipe format is an option anymore in drush 11/12: https://www.drush.org/12.x/output-formats-filters/
Maybe use --filter instead?

**Comment by joecorall** [comment]
Not sure if this is already fixed or not, but tested `make starter_dev` on https://github.com/Islandora-Devops/isle-dc/pull/384 and it works so once that PR merges I think we can close this issue.
