### ISSUE TITLE
make demo fails to build

### ISSUE THREAD

**Issue by MPavleski** [Islandora-Devops/isle-dc#355]
The command **make demo** fails in the  Development branch, commit 8b7e11cbc485eaf998d665d1e2ed68c0d4f41be0.

Relevant log:
`
docker compose exec -T drupal with-contenv bash -lc "drush si -y islandora_install_profile_demo --account-pass 'PASS'"

 You are about to:
 * DROP all tables in your 'drupal_default' database.

 // Do you want to continue?: yes.                                              

 [notice] Starting Drupal installation. This takes a while.
 [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile
 [error]  Error importing/updating configuration 
 [error]  Error importing/updating configuration 
 [notice] Performed install task: install_verify_requirements
 [notice] Performed install task: install_verify_database_ready
 [notice] Performed install task: install_base_system
 [notice] Performed install task: install_bootstrap_full
 [error]  The Flysystem driver is missing. 
 [warning] Could not find required jsonld.settings to add default RDF namespaces.
 [warning] The "views_block:members-block_1" was not found
 [notice] Performed install task: install_profile_modules
`

**Comment by joshdentremont** [comment]
Make demo has been removed as of https://github.com/Islandora-Devops/isle-dc/pull/363

You can now use make starter instead and then add demo content. https://islandora.github.io/documentation/installation/docker-local/#demo-content

This can be closed now.

**Comment by MPavleski** [comment]
Thank you @joshdentremont .
