### ISSUE TITLE
Drupal is blocked from checking available updates

### ISSUE THREAD

**Issue by kayakr** [Islandora-Devops/isle-dc#358]
I have "make local" partially working after a lot of hand-crafted fixes. Drupal won't report on https://islandora.traefik.me/admin/reports/updates "Failed to fetch available update data". Drupal watchdog has `GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: updates.drupal.org (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in GuzzleHttp\Handler\CurlFactory::createRejection() (line 200 of /var/www/drupal/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php).`

* `docker compose exec -T drupal with-contenv bash -lc "curl https://drupal/org"`
* `curl: (7) Failed to connect to drupal port 443 after 0 ms: Couldn't connect to server`

Is there some setting in traefik required for the Drupal container to reach out?

**Comment by joecorall** [comment]
Closing this due to a similar reason as https://github.com/Islandora-Devops/isle-dc/issues/364#issuecomment-2064174812
