### ISSUE TITLE
Certificate for the DNS may have expired

### ISSUE THREAD

**Issue by wilso929** [Islandora-Devops/isle-dc#371]
I and many of my team members are getting these errors when we try to build sites.

<img width="894" alt="Screenshot 2023-12-11 at 1 43 37 PM" src="https://github.com/Islandora-Devops/isle-dc/assets/94696454/0bed8a2c-b39f-4497-a72b-a55f9d52d9c2">

**Comment by ysuarez** [comment]
@wilso929 we are not sure why you are getting this issue.

I wanted to suggest that you run the `nslookup` CLI command (https://en.wikipedia.org/wiki/Nslookup) a couple of times, to see if it gives us useful information to troubleshoot what is going on 

After you run these 3 separate commands on your terminal, then send me the outputs through Slack (that way you don't share you internal name server IPs).

nslookup traefik.me

nslookup islandora.traefik.me

nslookup islandora.ca

Good luck,
Yamil Suarez (that is my name on the Islandora Slack)

**Comment by ysuarez** [comment]
This ticket was reviewed during today's weekly Islandora tech meeting. It was mentioned that traefik recently updated their cert, so this issue may have been resolved?

Let us know either way, so we can close this ticket by next week.

**Comment by ysuarez** [comment]
@wilso929 I will close this ticket because I did not hear back from you.

If you are still having issues please reach out to us on Slack or open up the ticket again.

**Comment by ysuarez** [comment]
Closing ticket.
