### ISSUE TITLE
Network gateway not found errors

### ISSUE THREAD

**Issue by aOelschlager** [Islandora-Devops/isle-dc#379]
I have not experienced this error myself, however, four people have now ran into this error and reported it on Slack. I'm not sure why it's happening but the docker compose file that is generated is declaring the gateway network as external and that causes the network to not be created thus giving this error. 
I know two of these were encountered on a vm. One had docker compose version one still installed. 

Temporary fix has been to edit the docker compose file and remove the external part for the gateway network. Next, comment out the line that generates the docker compose file in the Makefile. Then run make starter or starter_dev again.

**Comment by alxp** [comment]
I don't know enough about docker to speak confidently about what the correct thing to chagne it is, but another temporary workaround is to run the command 

```bash
docker network create gateway
```

and delete it with

```bash
docker network rm gateway
```

when not needed.

**Comment by ajstanley** [comment]
The problem seems to come from declaring external: true in the network definition instead of internal: false
[Docker docs.](https://docs.docker.com/reference/cli/docker/network/create/)

**Comment by joecorall** [comment]
Resolved by https://github.com/Islandora-Devops/isle-dc/pull/381
