### ISSUE TITLE
`make production` with latest islandora-starter-site failing

### ISSUE THREAD

**Issue by joecorall** [Islandora-Devops/isle-dc#392]
NIghtly build failing on `make production` with [`The "search_api_index" entity type does not exist.`](https://github.com/Islandora-Devops/isle-dc/actions/runs/8939078582/job/24554891533#step:10:130).

Not sure if an issue here or islandora-starter-site

**Comment by rosiel** [comment]
Is this a module race condition? I know that there are a number of non-fatal errors due to the order of module and config enabling... perhaps they finally caught up with us

**Comment by joecorall** [comment]
Yeah seems like a race. The nightly build sometimes succeeds and sometimes fails. Or _possibly_ a missed dependency for the `search_api` somewhere? The failure looks like maybe that module isn't installed or needs a cache flush to have it registered in Drupal's internals.

**Comment by DonRichards** [comment]
We could add this prior to hydrate and check if solr is ready
```makefile
docker-compose exec -T drupal with-contenv bash -lc "drush cr"
# Then check is solr is up before hydrating
@echo "Checking if Solr's healthy"
docker-compose exec -T solr bash -c 'curl -s http://localhost:8983/solr/admin/info/system?wt=json' | jq -r .lucene || (echo "Solr is not healthy, waiting 10 seconds." && sleep 10)
```
