### ISSUE TITLE
Don't enable Matomo by default

### ISSUE THREAD

**Issue by rosiel** [Islandora-Devops/isle-dc#395]
https://groups.google.com/g/islandora/c/MtHOxjew-tA

Stop installing Matomo by default in ISLE-DC, while leaving enough infrastructure in place that someone could turn it on, if desired.

**Comment by rosiel** [comment]
From the tech call: Ensure there's a minor version minted here to denote that matomo will be gone.

**Comment by joecorall** [comment]
Have a PR started for this here: https://github.com/Islandora-Devops/isle-dc/pull/396

> From the tech call: Ensure there's a minor version minted here to denote that matomo will be gone.

We don't have any semantic versioning in this repo, so not sure how best to communicate this change.
