### ISSUE TITLE
Point 'development' branch to ISLE-BuildKit 'main' tag

### ISSUE THREAD

**Issue by alxp** [Islandora-Devops/isle-dc#397]
n effort to reduce the work required for ISLE-DC to stay current, I propose having the 'development' branch of ISLE-DC use the 'main' tag for its ISLE-BuildKit images.

A further refinement of this could be to have releases which point to the corresponding tags, but I think anyone on a 'development' branch expects to be easily able to keep up with new image version.

Relatedly in a conversation on the [June 5, 2024 tech call](https://github.com/Islandora/islandora-community/wiki/June-5%2C-2024), some members believed that this was already the case so I think there's support for doing this.

**Comment by noahwsmith** [comment]
This seems like a really great improvement to me!
