### ISSUE TITLE
Add SYN to isle-fcrepo image

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-dc#40]
I think there is remaining work to add SYN and get it working in the isle-fcrepo image?

@dannylamb Apologies if you've already done this but I don't see any commits per se? 

https://github.com/Islandora-Devops/isle-fcrepo

**Comment by g7morris** [comment]
@dannylamb Just an FYI I've made some updates to this repo and you may want to refresh your local accordingly before posting a PR when you have the chance. Thanks.

**Comment by noahwsmith** [comment]
I assume this task is to complete the SYN configuration with a process similar to https://github.com/qadan/documentation/blob/installation/docs/installation/manual/installing_fedora_syn_and_blazegraph.md#syn

**Comment by g7morris** [comment]
There is currently the SSL script in `/scripts/fcrepo/` but I'm not clear on where the resulting keys should live. 

We're missing the config part `syn-settings.xml` and would need it added to `config/fcrepo`
