### ISSUE TITLE
Media migration error - SQLSTATE[40001]: Serialization failure

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-dc#50]
From @marksandford on Slack:

"I've gotten the test ingest files ready to go and zipped up.  Instructions are in the Readme, but it's basically installed as a module and a series of drush commands are run.

One caveat is that I consistently get `SQLSTATE[40001]: Serialization failure` when running the media migration.  Running it again with --update seems to fix it (as described in Readme).   Setting mysql to read-committed avoids the problem entirely, but I have no idea what the implications are for that in production, nor do I know if the ISLE config will differ in ways that will avoid the error" 

@dannylamb Have you run into this issue yet?

**Comment by g7morris** [comment]
@marksandford Perhaps you could include a few more details on the ticket when you have a chance?

What steps are you taking?

Is this the islandora-vagrant VM or the ansible-playbook? etc. etc. 

This way we can attempt to replicate on the upcoming merged ISLE docker stack. Thanks!

**Comment by marksandford** [comment]
I'm using the ansible playbook from here https://github.com/Islandora-Devops/islandora-playbook
Steps are running the playbook as per the readme in the repo, followed by ingesting objects using the zip file here https://drive.google.com/file/d/1T_zD40r6LRHvLyRlqaUCfYe6YjutCfnc/view?usp=sharing  The zip file is based on JHU's work, which in turn based on https://github.com/Islandora/migrate_islandora_csv

**Comment by g7morris** [comment]
This is no longer an issue due to work and improvements here https://github.com/Islandora-Devops/isle-buildkit. Please reopen ticket if this error arises again.
