### ISSUE TITLE
Review Docker Images& Services for S6 inclusion

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-dc#61]
From the April 23 weekly call, @nigelgbanks raised the idea of discussing potentially using [s6-overlay](https://github.com/just-containers/s6-overlay) for 

* @dbernstein seconded this for usage pushing log data in fcrepo to a logging service like Cloudtrail. 
* @g7morris pointed out that the ISLE 7 project uses this service extensively
  * https://github.com/Islandora-Collaboration-Group/isle-apache/blob/master/Dockerfile#L41

---

The task should be to identify which images and services could benefit from utilizing s6-overlay to help with process management especially child processes handling as well as piping logs to stdout (as needed)

Also reference this issue: [Logging to stderr / stdout for all images / containers / services #45](https://github.com/Islandora-Devops/isle-dc/issues/45)

**Comment by dannylamb** [comment]
I'm looking over the stack right now and seeing blank spots in config files in the pre-built images.  We're `envsubst`ing in the build process, and args aren't getting set right.  But that stuff probably shouldn't be in the build process anyway and we should use confd to template it out in the entrypoint.

If I'm gonna go as far as to do that, we should consider the whole s6/confd combo as an under-layer.  Off the top of my head, it'd be applicable to
- Houdini
- Hypercube
- Homarus
- Fcrepo
- Milliner
- Gemini
- CrayFits
- Recast
- Alpaca

And probably more, but that's the containers I'm familiar with.

I'm comfortable enough to attempt installing `confd` and trying my hand at that, but s6 I would just be blindly flailing about. Help with that would be appreciated.

**Comment by nigelgbanks** [comment]
Sorry for dropping off the radar and not posting sooner, when I went to do some cleanup on what I had locally over the weekend I ended up just spending the whole weekend on it. It's close to be done, but in the process of trying to tidy what I had I broke it. The general idea and layout is there but there are lots of bugs and things that need doing to make it work fully, I think about 2-3 days of work to get it in a good place.

https://github.com/nigelgbanks/docker-experiment

**Comment by dannylamb** [comment]
Oh snap you've got everything.  Yeah i'm sure it'll need to get looked over thoroughly as it gets wired up.  That's where our current implementation is at.

I'll take a deeper look :eyes: Thanks for dropping it off.

**Comment by g7morris** [comment]
As agreed on the weekly tech call, @nigelgbanks to give working demo for May 14th call for team review. Thanks @nigelgbanks for doing this. :+1:

**Comment by g7morris** [comment]
This work is now being done here https://github.com/Islandora-Devops/isle-buildkit. Closing ticket.
