### ISSUE TITLE
How can we help?

### ISSUE THREAD

**Issue by fabianderijk** [Islandora-Devops/isle-dc#62]
Hi,

The company I work for would like to start working with ISLE 8 ASAP. Is there some way we can help speed up the development? Is there a backlog of work? Can we do a small conference call to talk things through?

Ik would like to hear from you!

Thanks!

**Comment by noahwsmith** [comment]
Hi Fabian,

Ongoing project is here, with a pretty full issue queue:
https://github.com/Islandora-Devops/isle-dc/. We'd love to have your
support!

We have calls on Thursday at 1pm Eastern US time (so we just had one 3
hours ago - sorry to miss you). I'd be happy to have a direct conversation
about how you might get involved next week, if you're free? The easiest
place to find me and to be involved async is probably via Islandora
Foundation Slack - I'll invite you, and then I can connect you into the
working groups there too.

Cheers, ~Noah



--

Noah Smith

Founder + CEO

Pronouns: he/him/his. Scheduling a meeting with me? View my availability
<https://calendar.google.com/calendar/embed?src=noah.smith@commonmediainc.com&ctz=America/New_York&mode=WEEK>
Born-Digital | 84 Russell St, Hadley MA | (413) 259-6777 | born-digital.com

**Comment by noahwsmith** [comment]
Oh, I realize I can't invite you since I don't know your email. You can register here and find me as noahwsmith https://join.slack.com/t/islandora/shared_invite/zt-dphvbw8i-CvdQSwTEIp93TzLvor67pg

**Comment by g7morris** [comment]
Hello @fabianderijk , 

Just following up here on this ticket, to bring the new https://github.com/Islandora-Devops/isle-buildkit and associated efforts to your attention as well. 

Just repeating @noahwsmith 's invitation from above:

We have calls on Thursday at 1pm Eastern US time (including today). 

I don't know if you've already had a direct conversation with @noahwsmith yet about how you might get involved. The easiest place to find Noah and to be involved async is probably via Islandora
Foundation Slack - He can invite you, and then can connect you into the working groups there too.

Thanks. I'll leave this ticket open for another week but will close it then as we're cleaning up outstanding requests atm.

**Comment by joecorall** [comment]
Closing per the last comment in this ticket

> I'll leave this ticket open for another week but will close it then as we're cleaning up outstanding requests atm.
