### ISSUE TITLE
Islandora composer.json is missing dependencies

### ISSUE THREAD

**Issue by birkland** [Islandora-Devops/isle-dc#68]
Compared to an install via islandora-playbook, the composer.json file from
[Born-Digital-US/drupal-project](https://github.com/Islandora/drupal-project) is missing a couple dependencies:
```
"solarium/solarium": "^5.1",
"symfony/event-dispatcher": "4.3.4 as 3.4.99",
``` 

For now, it seems the best solution is to update the [Born-Digital-US/drupal-project](https://github.com/Islandora/drupal-project).

**Comment by g7morris** [comment]
Hi @birkland, 

Thanks for spotting this. 

I've refreshed the [Born-Digital-US/drupal-project](https://github.com/Born-Digital-US/drupal-project) fork with this [commit](https://github.com/Born-Digital-US/drupal-project/commit/f2a503b2bad4f820b2b0f96c3857ceacb445936b) adding those missing dependencies. 

Please retest as needed. 

Closing this ticket.
