### ISSUE TITLE
Makefile cannot build pre-existing codebases

### ISSUE THREAD

**Issue by birkland** [Islandora-Devops/isle-dc#69]
If you checkout an existing Drupal site into `codebase` and do `make`, the build will fail with

```
Composer could not find a composer.json file in /app
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
make: *** [Makefile:15: drupal_init] Error 1
```

**Comment by noahwsmith** [comment]
@nikathone can you propose an alternate command that will perform better?

**Comment by nikathone** [comment]
@noahwsmith this issue should be fixed once https://github.com/Islandora-Devops/isle-dc/pull/70 is merged. I did propose an alternative approach there and I will wait to see what @birkland think.

**Comment by birkland** [comment]
@noahwsmith I'm not sure I follow what "perform better" means, but there is the following:

The crux of the issue is that, as it stands, `composer` expects to see a `composer.json` in its working directory [here](https://github.com/Islandora-Devops/isle-dc/blob/development/scripts/drupal/init.sh#L182).  When running `composer` in Docker, its concept of "composer's working directory" is "whatever is mounted in `/app`", and this has already been chosen/fixed earlier in the script to be `isle-dc/`, not `isle-dc/codebase`  [here](https://github.com/Islandora-Devops/isle-dc/blob/development/scripts/drupal/init.sh#L143-L156), so the working directory is `isle-dc` instead of `isle-dc/codebase`.   Critically, the `cd` command [here](https://github.com/Islandora-Devops/isle-dc/blob/development/scripts/drupal/init.sh#L143-L156) has no effect when `composer` is run inside Docker, but _does_ make sense when running a system-local composer.  

My initial solution takes the approach "composer only needs to run in `codebase`, so just mount `isle-dc/codebase` as `/app` in Docker.  Then `composer` will always run in the directory it needs to be in".  It was the simplest solution that un-blocked me so I could just get past the issue and start working, and was consistent with my assumption that `codebase` was the one and only directory that ever would have anything in it that is relevant to `composer`.

The approach @nikathone puts forward makes a different assumption.  Its solution is "composer may need to be run in directories other than `codebase`, so we need to mount the current working directory (wherever that may be) as `/app` when we invoke `composer` in Docker".  It achieves this by calculating the docker run command for `composer` at runtime, when a function `composer_cmd` is invoked.  Critically, the `cd` command [here](https://github.com/Islandora-Devops/isle-dc/blob/development/scripts/drupal/init.sh#L143-L156) _does_ have an effect `composer` is run inside Docker, because the value of `$PWD` _at the time of invocation_, after the `cd`) determines the location of the `/app` mount in `composer_cmd` [here](https://gitlab.com/snippets/1971871#LC132).

**Comment by noahwsmith** [comment]
Ok- I'll stand by for Nia's update to https://github.com/Islandora-Devops/isle-dc/pull/70
