### ISSUE TITLE
Drupal Solr Search API module reporting issues now on wodby image post-merge

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-dc#76]
From https://github.com/Islandora-Devops/isle-dc/issues/21#issuecomment-624796276

Re-testing the current setup has revealed now that the current wodby image and the Drupal build are having the following issues.

* Drupal Report Status now indicating `You are using an incompatible Solr schema`

* Solr path needs to be `/` not `/solr`. 

This feels like something changed in the Drupal settings / code level. Putting back on the TO DO list for us to test / fix.

**Comment by nikathone** [comment]
@g7morris have you looked at https://www.drupal.org/project/search_api_solr/issues/3070455 especially if we are using drupal search api solr 4.x?

**Comment by g7morris** [comment]
@nikathone I think the question is if this can be fixed, should we move away from using wodby as the Solr image? (I've put you on this for both images to see what it reveals)
