### ISSUE TITLE
Running make in master branch results in 'Stop.'

### ISSUE THREAD

**Issue by mjordan** [Islandora-Devops/isle-dc#91]
When I run `make` in the development branch, make runs and generates the expected files. When I run it in the master branch (commit e48f21555f86fce3c9004b58b66621fd34fea3e2), this happens:

```
mark@mark-ThinkPad-X1-Carbon-6th:~/Documents/hacking/isle-dc$ make
make: *** No targets specified and no makefile found.  Stop.
```

Any suggestions?

**Comment by noahwsmith** [comment]
Master is WAY out of date - please do not use. @dannylamb should we delete that branch?

**Comment by dannylamb** [comment]
We can.  I believe we reference it in the README, which I can update.  Once we have a stable release, let's be cool and put it on `main` instead of `master`.

**Comment by dannylamb** [comment]
Done. I've updated the README here: https://github.com/Islandora-Devops/isle-dc/pull/96
