### ISSUE TITLE
ISLE runs slow on a Mac OSX 

### ISSUE THREAD

**Issue by bseeger** [Islandora-Devops/isle-dc#93]
I've been running a local setup on my Mac OSX (Catalina) and running into extremely long page load times.  The Manage->Extend page takes just shy of 30 seconds to load.   Many pages take at least 4 seconds to load.   It's a pretty awful developer experience. 

@birkland researched adding the `delegated` flag to the volume mount for the website codebase.  It seems promising and I'll submit a PR for that in a few minutes for other folks to try out.

**Comment by noahwsmith** [comment]
Another note: you can switch to DFM Edge to get better performance https://docs.docker.com/docker-for-mac/mutagen/

**Comment by nigelgbanks** [comment]
Fixed by the #94

**Comment by bseeger** [comment]
@noahwsmith  - thanks I'll check out DFM Edge.
