### ISSUE TITLE
https causing issues with iiif

### ISSUE THREAD

**Issue by DonRichards** [Islandora-Devops/isle-dc#98]
After ingesting a large tiff open seadragon shows a 500 error.

![Unable to open object Object HTTP o attempting to load TileSource](https://user-images.githubusercontent.com/2738244/88426985-16e8ec80-cdc0-11ea-925c-10fd8d481f6b.png)
Unable to open [object Object]: HTTP o attempting to load TileSource

First time visiting a site that implements an insecure https request will cause the media to load within Open Seadragon. 

__Quick solution__: is to go directly to https://islandora-isle-dc.12-34-56-78.traefik.me/cantaloupe/iiif/2 and accept the warning. This should probably be addressed, there is no obvious/simple indicator to the developer/user as to why the failure is happening.

![Screen Shot 2020-07-24 at 3 02 19 PM](https://user-images.githubusercontent.com/2738244/88427029-2f590700-cdc0-11ea-8894-6936fae0ff6d.png)

<img width="823" alt="Screen Shot 2020-07-20 at 8 45 33 AM" src="https://user-images.githubusercontent.com/2738244/87939033-6dbf9080-ca65-11ea-9450-97a92e43dbd1.png">

**Comment by DonRichards** [comment]
This is a case of a simple insecure ssl cert resulting in the browser blocking the content until you except the warning. To address this either a create a way the build triggers the warning, fix the cert, or add it to the documentation.

**Comment by DonRichards** [comment]
I as wrong about the workaround (sorta). You will need a fully qualified url. The URL to trigger the request needs to be a full IIIF request. Example: https://islandora-isle-dc.12-34-56-78.traefik.me/cantaloupe/iiif/2/http%3A%2F%2Fislandora-isle-dc-12-34-56-78.traefik.me%2Fsites%2Fdefault%2Ffiles%2F2020-07%2F1005-Service%2520File.jpg

**Comment by noahwsmith** [comment]
I can verify this issue, and I used the full URL you mentioned. And then I found another issue which is related - to use that fully qualified domain, the certs have to hold up. Some Ubuntu and Alpine distros require the fullchain.pem to allow CURL to work, so I issued a PR: https://github.com/Islandora-Devops/isle-dc/pull/103

**Comment by dannylamb** [comment]
@DonRichards https://github.com/Islandora-Devops/isle-dc/pull/103 has landed.  Does this solve the issue entirely?  Or just get rid of the warning from your browser?

**Comment by DonRichards** [comment]
@dannylamb going to test ASAP
